//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
            this.CustomerCoupons = new HashSet<CustomerCoupon>();
            this.OrderPromotions = new HashSet<OrderPromotion>();
        }
    
        public int CouponID { get; set; }
        public string CouponName { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> MaxDiscountAmount { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int UsageLimit { get; set; }
        public string CouponType { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> FixedDiscountAmount { get; set; }
        public decimal MinimumOrderValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsStackable { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string SourceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual MarketingCampaign MarketingCampaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotion> OrderPromotions { get; set; }
    }
}
