//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportReceiptDetail
    {
        public int DetailID { get; set; }
        public int ReceiptID { get; set; }
        public int ProductID { get; set; }
        public decimal ImportPrice { get; set; }
        public int ImportQuantity { get; set; }
        public int RemainingQuantity { get; set; }
    
        public virtual ImportReceipt ImportReceipt { get; set; }
        public virtual Product Product { get; set; }
    }
}
