//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportReceipt()
        {
            this.ImportReceiptDetails = new HashSet<ImportReceiptDetail>();
        }
    
        public int ReceiptID { get; set; }
        public Nullable<int> POID { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string ReceivedBy { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportReceiptDetail> ImportReceiptDetails { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
