//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPromotion
    {
        public int OrderPromotionID { get; set; }
        public int OrderID { get; set; }
        public string PromotionType { get; set; }
        public Nullable<int> CouponID { get; set; }
        public Nullable<int> CustomerCouponID { get; set; }
        public Nullable<int> ComboOfferID { get; set; }
        public string PromotionCode { get; set; }
        public decimal DiscountAmount { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ComboOffer ComboOffer { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual CustomerCoupon CustomerCoupon { get; set; }
        public virtual Order Order { get; set; }
    }
}
