//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int TransactionID { get; set; }
        public int OrderID { get; set; }
        public string PaymentGateway { get; set; }
        public string GatewayTransactionNo { get; set; }
        public decimal Amount { get; set; }
        public string ResponseCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
