//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceHistory
    {
        public int PriceHistoryID { get; set; }
        public int ProductID { get; set; }
        public decimal OldPrice { get; set; }
        public decimal NewPrice { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
