//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRecommendation
    {
        public int Id { get; set; }
        public int ProductID_A { get; set; }
        public int ProductID_B { get; set; }
        public decimal Confidence { get; set; }
        public int Support { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
