//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int VariantID { get; set; }
        public int ProductID { get; set; }
        public string SKU { get; set; }
        public string VariantAttributes { get; set; }
        public decimal VariantPrice { get; set; }
        public int StockQuantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
