//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBehaviorLog
    {
        public int LogID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ActionType { get; set; }
        public int ActionWeight { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string SearchKeyword { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
