//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComboOffer()
        {
            this.OrderPromotions = new HashSet<OrderPromotion>();
        }
    
        public int ComboOfferID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public int ProductID_A { get; set; }
        public int ProductID_B { get; set; }
        public string Code { get; set; }
        public decimal DiscountAmount { get; set; }
        public int Support { get; set; }
        public decimal Confidence { get; set; }
        public decimal ActualUtility { get; set; }
        public decimal MinimumMarginPct { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int UsageLimit { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MarketingCampaign MarketingCampaign { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotion> OrderPromotions { get; set; }
    }
}
