//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCoupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCoupon()
        {
            this.OrderPromotions = new HashSet<OrderPromotion>();
        }
    
        public int CustomerCouponID { get; set; }
        public int CouponID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> TargetProductID { get; set; }
        public string TriggerType { get; set; }
        public decimal InterestScore { get; set; }
        public string Status { get; set; }
        public System.DateTime AssignedAt { get; set; }
        public Nullable<System.DateTime> ViewedAt { get; set; }
        public Nullable<System.DateTime> ClickedAt { get; set; }
        public Nullable<System.DateTime> AddedToCartAt { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPromotion> OrderPromotions { get; set; }
    }
}
